### ISSUE TITLE
Close input on <Esc>

### ISSUE THREAD

**Issue by bsander** [stevearc/dressing.nvim#1]
This plugin looks great! I have a hard time canceling a rename operation though, pressing Escape just changes to normal mode but doesn't close the rename input modal. Seems like I need to explicitly close the window for that. Am I missing something? I think pressing Escape should close the window and cancel the renaming.

**Comment by mel10c** [comment]
Yeah, seems that this problem is only present for the `input` section, the `selection` section would work exist properly with <esc>.

**Comment by stevearc** [comment]
Sounds like a good idea to me!

**Comment by axieax** [comment]
Hello, not sure but can anyone else reproduce this issue? I'm trying to use vim.lsp.buf.rename.
https://user-images.githubusercontent.com/62098008/144731838-2aa1e938-14e4-43f7-b32d-cc093645446f.mp4

**Comment by stevearc** [comment]
Apologies, should be fixed now. I was using a `:command` mapping instead of `<cmd>` to force the completion window to close (if it was visible), but that caused this issue. Refactored it to close the window in a more reliable way.
