### ISSUE TITLE
Run FZF cancel callback based on v:event

### ISSUE THREAD

**Issue by gbrlsnchs** [stevearc/dressing.nvim#10]
Inspired by this plugin, I'm experimenting with `fzf#run` myself, and its terminal command returns `1` if there's an error with the command or `130` if nothing is chosen (I tested pressing both <kbd>Esc</kbd> and <kbd>Ctrl</kbd>+<kbd>C</kbd>).

Therefore, you can check `v:event` to capture the `fzf` command exit status and only run the cancel callback when the status is not `0` (or only when it's `130` depending on how you want to handle errors). You can do that in a `TermClose` autocmd, instead of deferring a callback using `BufLeave`.

**Comment by stevearc** [comment]
Yeah, I do like that better than the deferred function. Thanks for the tip!
