### ISSUE TITLE
Input windows covers the current line when using NW anchor

### ISSUE THREAD

**Issue by queezle42** [stevearc/dressing.nvim#106]
**Describe the bug**
`vim.ui.input` window (e.g. for LSP rename) covers the cursor / current line when configuring `input.anchor = "NW"`.

**System information**

- OS: linux (NixOS)
- Neovim version: 0.9.1
- Dressing config:

```lua
require("dressing").setup {
  input = {
    insert_only = false,
    anchor = "NW",
    mappings = {
      n = {
        ["<C-k>"] = "HistoryPrev",
        ["<C-j>"] = "HistoryNext",
      },
      i = {
        ["<C-k>"] = "HistoryPrev",
        ["<C-j>"] = "HistoryNext",
      },
    },
  },
}
```

**Screenshots**
![image](https://github.com/stevearc/dressing.nvim/assets/1024891/2d59f989-dc3d-4e74-9597-aadf13b34294)
![image](https://github.com/stevearc/dressing.nvim/assets/1024891/3758bdc5-ffae-4fb4-8ca7-852dd3e7bdc6)

**Additional context**
From `:help nvim_open_win`:
```
• bufpos: Places float relative to buffer text (only when
  relative="win"). Takes a tuple of zero-indexed [line,
  column]. `row` and `col` if given are applied relative
  to this position, else they default to:
  • `row=1` and `col=0` if `anchor` is "NW" or "NE"
  • `row=0` and `col=0` if `anchor` is "SW" or "SE" (thus
    like a tooltip near the buffer text).
```

In input.lua, `row` is set, so the `row=1` offset is lost: https://github.com/stevearc/dressing.nvim/blob/39611852fd7bbac117e939a26759bb37361f0c90/lua/dressing/input.lua#L249

Possible fixes include:
- Using `bufpos` instead of `row`/`col` (this seems to be the intended way to position a window relative to buffer text)
- Not setting `row`/`col` when using `relative="cursor"`
- Update `calculate_row` to check the `anchor`. I did that before fully understanding the alternatives (I'll open a PR).

**Comment by stevearc** [comment]
Honestly, the anchor should not even be a config option anymore. It's left over from a time when there were more ways to configure the `nvim_open_win` by passing in static values. That was brittle and not very flexible, so I added the `override` function as a config option, which allows you to take the options that dressing calculates and perform whatever mutations you want to it. It's much more flexible, and simpler to boot.

**Comment by ehaynes99** [comment]
I used to use this so that it would display under the cursor. Any idea what I should use now?
```lua
{
  input = {
    anchor = 'NW',
    override = function(conf)
      -- display under cursor, not on top of it
      if conf.anchor == 'NW' and (conf.row == nil or conf.row == 0) then
        conf.row = 1
      end
      return conf
    end,
  },
}
```
![image](https://github.com/stevearc/dressing.nvim/assets/2187664/d49da30b-847c-4a4c-9600-43be90e21ab2)

**Comment by stevearc** [comment]
@ehaynes99 you can set the anchor in the override function like so:
```lua
      override = function(conf)
        conf.anchor = "NW"
        conf.row = 1
      end
```
