### ISSUE TITLE
No whitespaces between titles with builtin provider

### ISSUE THREAD

**Issue by vollowx** [stevearc/dressing.nvim#109]
**Describe the bug**
There are whitespaces between window titles in the README images, but not in the installed NeoVim/

**System information**

- OS: linux
- Neovim version: v0.10.0-dev-b74262a
- `vim.ui.select` backend: `builtin`
- Dressing config:

```lua
local border = require('core.settings').border -- 'single' in this case
require('dressing').setup {
  input = {
    border = border,
    win_options = {
      winblend = 0,
    },
  },
  select = {
    backend = 'builtin',
    builtin = {
      border = border,
      relative = 'cursor',
      win_options = {
        winblend = 0,
      },
      min_height = { 0, 0 },
    },
  },
}
```

**To Reproduce**

1. Rename, select code actions or something else to open `dressing` features

**Screenshots**
Currently have no screenshot tools in my computer

**Additional context**
Provide a option like `space_between_title` or let user format the title by themselves.

**Comment by stevearc** [comment]
I've added the surrounding whitespace back to the title text

**Comment by vollowx** [comment]
Thanks
