### ISSUE TITLE
hey yo! disable ```dressing.nvim``` in ```nvim-tree``` float window

### ISSUE THREAD

**Issue by daUnknownCoder** [stevearc/dressing.nvim#122]
**Describe the bug**
I Personally like Nvim-Tree in a float window in the center of the screen. When i use ```a``` or ```d``` or any key in nvim-tree, it closes nvim-tree and i again have to open it and all its a fuss and i dont like it, so any option to disable ```dressing.nvim``` for a certain filetype would be awesome

**System information**

- OS: [arch linux]

```
Neovim version:
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
 ```
- Dressing config:

```lua
  {
    "stevearc/dressing.nvim",
    event = "BufReadPost",
    lazy = true,
    opts = {
      select = { backend = { "telescope", "builtin" } },
    },
    config = function(_, opts)
      require("dressing").setup(opts)
      -- luacheck: ignore 113
    end,
  },
```
i also tried : 
```lua
 vim.cmd([[autocmd FileType NvimTree let g:dressing_disable = v:true]]), but it didnt work out ig
``` 

**Video**

https://github.com/stevearc/dressing.nvim/assets/84800625/87751358-eeb4-4d89-aefb-b233a265bdfb

check this video, dressing is lazy loaded on ```BufReadPost``` and ```BufNewFile``` so on startup, pressing ```a``` in ```nvim-tree``` gives me an input dialog, after opening a file, pressing ```a``` in ```nvim-tree``` gives me the dressing dialog which is not good, so can i disable it?

**Comment by stevearc** [comment]
Try this https://github.com/stevearc/dressing.nvim/issues/29#issuecomment-1076985525

**Comment by daUnknownCoder** [comment]
> Try this [#29 (comment)](https://github.com/stevearc/dressing.nvim/issues/29#issuecomment-1076985525)

thanks bro, didnt scroll down to check this in the 29th issue...

**Comment by swahpy** [comment]
Hi, I have the same issue now. But I'm thinging if it's possible to keep both nvim-tree and dressing open at the same time. Thank you for any hints.

**Comment by daUnknownCoder** [comment]
> Hi, I have the same issue now. But I'm thinging if it's possible to keep both nvim-tree and dressing open at the same time. Thank you for any hints.

so i m using this:
```lua
return {
  "stevearc/dressing.nvim",
  lazy = false,
  event = "VeryLazy",
  config = function()
    local status_ok, dressing = pcall(require, "dressing")
    if not status_ok then
      print("dressing not found!")
    end
    dressing.setup({
      input = {
        get_config = function()
          if vim.api.nvim_buf_get_option(0, "filetype") == "NvimTree" then
            return { enabled = false }
          end
        end,
      },
      select = {
        backend = { "telescope", "builtin" },
        get_config = function()
          if vim.api.nvim_buf_get_option(0, "filetype") == "NvimTree" then
            return { enabled = false }
          end
        end,
      },
    })
  end,
}
```

**Comment by swahpy** [comment]
> > Hi, I have the same issue now. But I'm thinging if it's possible to keep both nvim-tree and dressing open at the same time. Thank you for any hints.
> 
> so i m using this:
> ...
Thank you for your reply. I just found that for the same configuration, I can keep both dressing and nvim-tree open on my mac, while it doesn't work on debian linux. It is really strang. Let me try your solution to disable it during nvim-tree open.
