### ISSUE TITLE
Question: how to detect if `vim.ui.input` is been patched by this plugin via lua?

### ISSUE THREAD

**Issue by linrongbin16** [stevearc/dressing.nvim#125]
Hi, is there a way to detect if `vim.ui.input` is been patched by this plugin, or I'm using the builtin neovim's `vim.ui.input`?

**Comment by stevearc** [comment]
There's not a great way to do so. What are you trying to accomplish?

**Comment by linrongbin16** [comment]
emmm, I should close this issue for now, maybe after I come up with a minimal init lua that can re-produce the issue that I want to show.
