### ISSUE TITLE
Compatibility issue with telescope-file-browser

### ISSUE THREAD

**Issue by AckslD** [stevearc/dressing.nvim#13]
Using `dressing.nvim` and `telescope-file-browser` at the same time seems to not be possible at the moment, see this issue:
https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/66

It seems that the issue is that `dressing` triggers a `BufLeave` event which closes the `telescope` buffer. I'm not sure how easy that could be to fix but an alternative could maybe be to have the ability to disable `dressing` under certain circumstances, eg for `telescope` buffers.

**Comment by stevearc** [comment]
Disabled autocmds when opening the modal, so it should work fine now. I don't *think* there's any use case for those autocmds, but if this breaks anyone's workflow comment here and we'll see what we can do.

**Comment by AckslD** [comment]
@stevearc awesome :tada:, can confirm it works
