### ISSUE TITLE
nui vim.ui.select callback is called twice,

### ISSUE THREAD

**Issue by DrKGD** [stevearc/dressing.nvim#131]
**Describe the bug**
NUI vim.ui.select callback is called twice, once for "on_close" and once for "on_submit", not sure if that has always been the case but I just happened to discover it.

[NUI Integration in dressing.nvim](https://github.com/stevearc/dressing.nvim/blob/master/lua/dressing/select/nui.lua#L50)

**System information**

- OS: Arch Linux
- Neovim version: NVIM v0.10.0-dev-1840+g97bea3163a
- Is this related to a specific `vim.ui.select` backend? If so, which one? NUI
- Dressing config:

```lua
require('dressing').setup {
  select = {
    backend = { "nui", "fzf_lua", "builtin" },
  }
}
```

Of course, thats the MRE for me, using lazy.nvim, without lazy loading.

**To Reproduce**

1. Run the following
```:lua vim.ui.select({'a','b'}, { prompt = 'test' }, function(input) print(input) end)```
2. Either cancel with Esc, or confirm any of its values, should report both the value itself and an extra nil

![image](https://github.com/stevearc/dressing.nvim/assets/44092476/9e1774c6-1cd1-4e3b-b0cf-507ca2c335c3)

By commenting out `on_close`, nui integration works as intended, not sure if that bring any side effects into the mix :disappointed:

**Comment by stevearc** [comment]
Should be fixed
