### ISSUE TITLE
[Question] option to disable titles

### ISSUE THREAD

**Issue by sand4rt** [stevearc/dressing.nvim#133]
Thanks for the awesome plugin! 

Do you know if there is an option to disable all the titles? In this case "New Name:":
<img width="436" alt="Screenshot 2024-01-07 at 00 58 22" src="https://github.com/stevearc/dressing.nvim/assets/17591696/0c9cc73e-0008-4d3b-9d4b-bb8c6cf528d6">

**Comment by stevearc** [comment]
There is no way to disable the titles. Part of the interface for `vim.ui.input` is providing prompt text, so the plugin author or whoever is calling `vim.ui.input` is assuming that you will be able to read the prompt. In some cases maybe it isn't important, but we can't make the assumption that it's never important. As far as I'm concerned, displaying the prompt is part of the API contract for `vim.ui.input`.

**Comment by sand4rt** [comment]
I ended up using:

```lua
-- LazyVim config
return {
	"stevearc/dressing.nvim",
	event = "VeryLazy",
	config = function()
		require("dressing").setup({
			input = {
				border = "single",
			},
			select = {
				enabled = false,
			},
		})
		local input = vim.ui.input
		vim.ui.input = function(opts, on_confirm)
			opts.prompt = ""
			input(opts, on_confirm)
		end
	end,
}
```
