### ISSUE TITLE
(select) Telescope code actions failed

### ISSUE THREAD

**Issue by AlejandroSuero** [stevearc/dressing.nvim#140]
**Describe the bug**
When I use code actions to open the available ones I get the following error

```bash
Error executing vim.schedule lua callback: ...vim/lazy/dressing.nvim/lua/dressing/select/telescope.lua:29: attempt to index field 'ctx' (a nil value)
stack traceback:
        ...vim/lazy/dressing.nvim/lua/dressing/select/telescope.lua:29: in function <...vim/lazy/dressing.nvim/lua/dressing/select/telescope.lua:8>
        ...vim/lazy/dressing.nvim/lua/dressing/select/telescope.lua:137: in function 'select'
        ...are/nvim/lazy/dressing.nvim/lua/dressing/select/init.lua:74: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**System information**

- OS: [ubuntu on WSL]
- Neovim version: v0.10.0
- Is this related to a specific `vim.ui.select` backend? If so, which one? Telescope 
- Dressing config: with lazy.nvim

```lua
return {
  "stevearc/dressing.nvim",
  event = "VeryLazy",
  config = true,
}
```

with or without `config = true`, still errors

```lua
-- Paste your call to require("dressing").setup(...) in here
```

**To Reproduce**

1. Go to a diagnostic that requires a code action
  - In my case:
  
```lua
-- some code
file = io.open(options, "w")
file:write(new_content) -- Diagnostic: Need check nil
file:close() -- Diagnostic: Need check nil
-- more code
```

2. Use `vim.lsp.buf.code_action`
3. Errors

If possible, provide a minimal file that will trigger the issue (see
[tests/manual](https://github.com/stevearc/dressing.nvim/tree/master/tests/manual)
for examples of short ways to call `vim.ui.*`):

```
minimal code here
```

**Screenshots**

![image](https://github.com/stevearc/dressing.nvim/assets/71392160/189dd096-09cf-4b50-a391-1b9c90eccdfb)

![image](https://github.com/stevearc/dressing.nvim/assets/71392160/0f49bb03-c8e9-4b95-86a1-0d0d16e9df56)

![image](https://github.com/stevearc/dressing.nvim/assets/71392160/ee6cd074-abb2-4631-b844-7256e0919d6f)

Also in a `.c` file:

![image](https://github.com/stevearc/dressing.nvim/assets/71392160/a4830299-3d24-42a6-a793-7958feb921ac)

![image](https://github.com/stevearc/dressing.nvim/assets/71392160/8b1f9583-5ca4-48e0-aa64-b165abd047a4)

**Additional context**
On Windows11 (my host machine) seems to be working fine

**Comment by AlejandroSuero** [comment]
# An update on the issue

My host machine **Windows11** has the version **v0.9.2**.

In my **Ubuntu on WSL** with the **v0.10.0** if I introduce the `vim.ui.select` from the nvim docs.

```lua
     vim.ui.select({ 'tabs', 'spaces' }, {
         prompt = 'Select tabs or spaces:',
         format_item = function(item)
             return "I'd like to choose " .. item
         end,
     }, function(choice)
         if choice == 'spaces' then
             vim.o.expandtab = true
         else
             vim.o.expandtab = false
         end
     end)
```

It shows the select window properly.

![image](https://github.com/stevearc/dressing.nvim/assets/71392160/f8f3a32c-5014-46e2-b245-c56216dffa41)

**Comment by stevearc** [comment]
What is the specific version of Neovim where you see this issue? I am unable to repro using `NVIM v0.10.0-dev-2143+g3f188bc53`. Also double check that you are on the most recent version of dressing.nvim

**Comment by AlejandroSuero** [comment]
My version of Neovim where the issue ocurres is `NVIM v0.10.0-dev-619+gf771d6247`

I just lazy synced and my current dressing version is the one attached to 7237cdf and still has the same issue.

I will update Neovim  and see if happens.

**Comment by AlejandroSuero** [comment]
I updated to the latest version `NVIM v0.10.0-dev-2143+g3f188bc53`

Now seems to be working perfectly fine.
