### ISSUE TITLE
Incorrect installation snippet for Lazy.nvim

### ISSUE THREAD

**Issue by kjkent** [stevearc/dressing.nvim#153]
The plugin code for Lazy.nvim needs to be a return statement :)  
```Lua
return {
    'stevearc/dressing.nvim',
    opts = {},
}
```
Many thanks to stevearc and all the collaborators!

**Comment by stevearc** [comment]
It only needs to be a return if you put it in a file by itself. I have no idea if you're going to put this in a separate file or include it in a larger list of plugins, so I'm keeping the structure agnostic.
