### ISSUE TITLE
Suggestion: Make `input.insert_only = false` the default

### ISSUE THREAD

**Issue by chrisgrieser** [stevearc/dressing.nvim#163]
I often get asked by other people how to get vim motions while editing input, and my answer is this to recommend them dressing.

Considering that this is one of the selling points of this plugin, I think `input.insert_only = false` should be the default.

**Comment by stevearc** [comment]
`insert_only = true` was a mistake from the beginning; suggested by someone else and I was too inexperienced a maintainer to push back on it. I'm happy to do this
