### ISSUE TITLE
lsp rename needs to hit esc twice, one for exit insert mode, another for  cancel the input

### ISSUE THREAD

**Issue by GopherJ** [stevearc/dressing.nvim#173]
**Describe the bug**

**System information**

- OS: [windows/linux/mac]
- Neovim version:
- Is this related to a specific `vim.ui.select` backend? If so, which one?
- Dressing config:

```lua
-- Paste your call to require("dressing").setup(...) in here
```

**To Reproduce**

1.
2.
3.

If possible, provide a minimal file that will trigger the issue (see
[tests/manual](https://github.com/stevearc/dressing.nvim/tree/master/tests/manual)
for examples of short ways to call `vim.ui.*`):

```
minimal code here
```

**Screenshots**

**Additional context**

**Comment by Finistere** [comment]
Had a similar issue, had both `telescope` and `nui-nvim`. Removed the later and it just worked again.

**Comment by stevearc** [comment]
LSP rename uses `vim.ui.input`. The input window starts in insert mode, so the first `<ESC>` changes to normal mode and the second `<ESC>` cancels the modal. You are welcome to make an insert-mode mapping to close the window on `<ESC>`, or you can use the built-in mapping of `<C-c>` to close it.
