### ISSUE TITLE
Weird input prompt behavior

### ISSUE THREAD

**Issue by Lopi-py** [stevearc/dressing.nvim#18]
https://gyazo.com/038fd26af21cfb8e3661c57ceab0dcf6
Sometimes when the cursor is at top, input prompt acts weird.

**Comment by stevearc** [comment]
Hmmmm...this looks like some behavior I was seeing before I added a `defer` to the creation of the float title. I'm having some trouble getting it to repro now, could you tell me:
* What are you doing exactly to bring up the modal?
* What version of Neovim are you on?
* Does this only happen when your cursor is on the top line?

**Comment by Lopi-py** [comment]
* `:lua vim.ui.input({ prompt = "text" }, function() end)`
* `NVIM v0.7.0-dev+991-g547497b04`
* No, now I have noticed that it's random

**Comment by stevearc** [comment]
This is fundamentally working around a bug in neovim (https://github.com/neovim/neovim/issues/13403), but I swapped out the `defer_fn` hack for a different hack that should hopefully be more robust. Give it a try and see if it fixes the issue

**Comment by Lopi-py** [comment]
Yes, it's fixed, thanks
