### ISSUE TITLE
Complete the source issue

### ISSUE THREAD

**Issue by Tridays** [stevearc/dressing.nvim#183]
In this file, 'dressing. nvim/lua/pressing/input.lua'
The source for completion is sources, which should be added by the user themselves. The suggestion is: sources=opts.source. If it is empty, use the built-in completion source

--------------------------------------------------------------------------------------------------input.lua
  -- Configure nvim-cmp if installed
  local has_cmp, cmp = pcall(require, "cmp")
  if has_cmp then
    cmp.setup.buffer({
      enabled = opts.completion ~= nil,
      sources = {
        { name = "omni" },  --Hard coding, this is very unfriendly
      },
    })
  end

--------------------------------------------------------------------------------------------------
for example:

  vim.ui.input({
                                prompt = "Title",
                                completion = true,  --Activate completion function
                                sources = {“path”, "buffer"}，--Set more sources 
                                telescope = require("telescope.themes").get_cursor(),
                            },
                            function(input)
                                print(input)
                            end)

**Comment by stevearc** [comment]
The reason it is hard coded to `omni` is because we also set `omnifunc` when a `completion` argument is passed to vim.ui.input.

https://github.com/stevearc/dressing.nvim/blob/43b8f74e0b1e3f41e51f640f8efa3bcd401cea0d/lua/dressing/input.lua#L505-L507

This is what allows the callsite for vim.ui.input to customize the completion.
