### ISSUE TITLE
Center input?

### ISSUE THREAD

**Issue by tami5** [stevearc/dressing.nvim#19]
Hello @stevearc, smart plugin. great work.

I'm currently testing it for inputs but I fail to make the window center, relative to the buffer or the window. I wonder there is away to do this or an option available 

Thanks ❤️

**Comment by stevearc** [comment]
Yep, I could add that as an option. I'm about to travel, so I won't be able to get to it until next week, though.

**Comment by tami5** [comment]
> Yep, I could add that as an option. I'm about to travel, so I won't be able to get to it until next week, though.

That would be great. Take care @stevearc

**Comment by stevearc** [comment]
Added some more layout possibilities. You can now center the input window relative to the current window or to the entire editor with the `relative` option:
```lua
require('dressing').setup({
  input = {
    relative = 'win', -- or 'editor'
  },
}
```

**Comment by tami5** [comment]
😍  Thanks @stevearc ❤️
