### ISSUE TITLE
Input prompt alignment

### ISSUE THREAD

**Issue by mbenford** [stevearc/dressing.nvim#27]
I see that there is already [support for customizing the input prompt alignment](https://github.com/stevearc/dressing.nvim/blob/96552c9199dc4e169d1c54a21300365ffa483da9/lua/dressing/util.lua#L116), but it is currently not exposed and alignment is [hard-coded](https://github.com/stevearc/dressing.nvim/blob/96552c9199dc4e169d1c54a21300365ffa483da9/lua/dressing/input.lua#L296) as `left`. Will it be eventually promoted to a public option that we can use?

**Comment by stevearc** [comment]
Added! Set it with
```lua
require('dressing').setup({
  input = {
    prompt_align = 'left',
  }
})
```

**Comment by mbenford** [comment]
Whoa, thanks for such a quick reply! It works perfectly! :)
