### ISSUE TITLE
Add normal mode for input.

### ISSUE THREAD

**Issue by jandamm** [stevearc/dressing.nvim#3]
I've seen #1.
But I see value in having ESC exiting insert mode.
Pressing ESC again would then close the prompt.

I guess it wouldn't be too alienating for many users since this is his telescope works as well.
Ideally this would be an option which could be set in `get_config` for input.

On another note, is there a filetype assigned to the input buffer which can be used to apply custom mappings?
This might not "fix" but help with #2.

**Comment by stevearc** [comment]
I like both of these suggestions! Will add them shortly.

**Comment by stevearc** [comment]
Added an option to disable the '<Esc> in insert closes' mapping and set the filetypes of `DressingInput` and `DressingSelect` on the built-in modals.

**Comment by jandamm** [comment]
Awesome, thank you 🙏
