### ISSUE TITLE
CursorLine highlight in builtin select overwritten ?

### ISSUE THREAD

**Issue by fitrh** [stevearc/dressing.nvim#30]
![20220329_234801_full](https://user-images.githubusercontent.com/55179750/160654362-bba51978-c0cd-4992-8927-534d73206215.jpg)

I'm using tokyonight.nvim colorschme, and it seems for builtin select window, the CursorLine overwritten in the text, is this expected ?

**Comment by stevearc** [comment]
It was a side effect of how I was applying some custom highlight groups. After investigating, that logic isn't necessary to customize the color of the text, and has several negative side effects (this being one of them). I've removed that logic and added a deprecation warning. CursorLine should display properly for you now.

**Comment by fitrh** [comment]
Thank you
