### ISSUE TITLE
Open menu before loading buffer

### ISSUE THREAD

**Issue by ChristianChiarulli** [stevearc/dressing.nvim#34]
I am using a language server that I need to make a selection for before starting the server. Currently I can use the default way to select my option first and then the buffer loads. When using this plugin the buffer is not blocked from loading and I am unable to make the selection before the language server starts.

Is there anyway to expose an option to have the menu block loading a buffer until after the selection is made?

buffer is not loaded yet, there is time to make selection
![image](https://user-images.githubusercontent.com/29136904/160977973-cc86874d-bc32-4ae2-8faf-626e6a0d48f6.png)

buffer already loaded, too late to make selection
![image](https://user-images.githubusercontent.com/29136904/160978083-8324b696-67ab-413a-a9b4-63766c636e28.png)

**Comment by stevearc** [comment]
Unfortunately, there's no way to block it in the same way that `inputlist()` would. When vim uses those built-in input commands, the whole editor more-or-less is paused while that resolves. Even if there were an API to do a similar pause, that would also block the rendering of the selection float.

That said, there are some other possibilities.
* You could conditionally disable the `vim.ui.select` patch and use the built-in `inputlist()` function for this particular case. See #29 for more info.
* Total hack, but you could play around with doing an immediate `bufwipe` or `bufclose`, popping up the prompt, then reloading the buffer (with a flag to prevent an infinite loop).
* If this is for LSP, you have the option to take more control over when the client attaches. You could pass `autostart = false` to your configuration and run `:LspStart` once the selection completes.
