### ISSUE TITLE
Text Artifacts in Rename Window with Rust Attributes

### ISSUE THREAD

**Issue by theduke** [stevearc/dressing.nvim#35]
**Describe the bug**

I just tried out dressing and I'm getting text artifacts in the rename window when the line above the to be renamed item has Rust attributes. See below for example code.

The green text below is the artifact, it should just say `Webpage`.
The extra text is overwritten and disappears when typing over it.

![2022-04-14T18:26:28+02:00](https://user-images.githubusercontent.com/241621/163436143-bf672fd1-00e5-4cbb-96fe-f2ad1ff0fa17.png)

**System information**

- OS: Linux
- Neovim version: 0.6.1
- Dressing config: default config, no changes 

```lua
require('dressing').setup({})
```

**To Reproduce**

1. Open a Rust file
2. Trigger lsp rename (on `Webpage` below)

```rust
#[derive(Serialize, Deserialize, Entity, Clone)]
#[factor(namespace = "semantic")]
pub struct Webpage {
}
```

**Additional context**

The relevant LSP is rust-analyzer, if that makes any difference.

**Comment by stevearc** [comment]
It looks like your terminal may not support the fake transparency? Try setting winblend = 0
```lua
require('dressing').setup({
  input = {
    winblend = 0
  }
})
```

**Comment by theduke** [comment]
Yeah, that was it indeed.

The terminal is [kitty](https://github.com/kovidgoyal/kitty).

**Comment by theduke** [comment]
Since Kitty is fairly popular, maybe a note in the README would be good.

**Comment by stevearc** [comment]
Huh... that's interesting because I use kitty. Perhaps it's the font you're using? I will admit I am no expert on terminal rendering

**Comment by theduke** [comment]
Also relatively odd. I'm using `DejaVu Sans Mono`, so a pretty standard font.

I'm using the Sway Wayland compositor, maybe that's related.
