### ISSUE TITLE
vim.ui.input reports nil for empty string

### ISSUE THREAD

**Issue by Shatur** [stevearc/dressing.nvim#40]
**Describe the bug**

The following code

```lua
vim.ui.input({ prompt = 'Data: ' }, function(data) vim.notify(vim.inspect(data)) end)
```

prints `nil` for both cancelled dialog and empty input. I would expect to have an empty string on empty input.

**System information**

- OS: linux
- Neovim version: 0.7
- Dressing config: defaults

**To Reproduce**

1. `:vim.ui.input({ prompt = 'Data: ' }, function(data) vim.notify(vim.inspect(data)) end)`
2. Press `<CR>`

**Comment by stevearc** [comment]
This is intentional behavior. The built-in `vim.ui.input` explicitly treats an empty return string as `nil`, so we have to do the same to preserve compatibility.
https://github.com/neovim/neovim/blob/0adc66171a355a12494d87ebb767d509540c7ef9/runtime/lua/vim/ui.lua#L92-L96

**Comment by Shatur** [comment]
Oh, I see... But how can I know if a user canceled the dialog or set an empty string?

**Comment by stevearc** [comment]
Unfortunately, you cannot. I believe this is a limitation of the `input()` function, which seems to return an empty string when canceled. Since it can't distinguish between empty input and cancel, `vim.ui.input` can't either.
