### ISSUE TITLE
Difficult to see Input border and title

### ISSUE THREAD

**Issue by Firaenix** [stevearc/dressing.nvim#42]
**System information**

- OS: mac
- Neovim version: 0.7
- Dressing config:

```lua
require('dressing').setup({
  input = {
    -- Set to false to disable the vim.ui.input implementation
    enabled = true,

    -- Default prompt string
    default_prompt = "Input:",

    -- Can be 'left', 'right', or 'center'
    prompt_align = "left",

    -- When true, <Esc> will close the modal
    insert_only = true,

    -- These are passed to nvim_open_win
    anchor = "SW",
    border = "rounded",
    -- 'editor' and 'win' will default to being centered
    relative = "cursor",

    -- These can be integers or a float between 0 and 1 (e.g. 0.4 for 40%)
    prefer_width = 40,
    width = nil,
    -- min_width and max_width can be a list of mixed types.
    -- min_width = {20, 0.2} means "the greater of 20 columns or 20% of total"
    max_width = { 140, 0.9 },
    min_width = { 80, 0.2 },

    -- Window transparency (0-100)
    winblend = 0,
    -- Change default highlight groups (see :help winhl)
    winhighlight = "",

    override = function(conf)
      -- This is the config that will be passed to nvim_open_win.
      -- Change values here to customize the layout
      return conf
    end,

    -- see :help dressing_get_config
    get_config = nil,
  },
  select = {
    -- Set to false to disable the vim.ui.select implementation
    enabled = true,

    -- Priority list of preferred vim.select implementations
    backend = { "telescope", "fzf_lua", "fzf", "builtin", "nui" },

    -- Trim trailing `:` from prompt
    trim_prompt = true,

    -- Options for telescope selector
    -- These are passed into the telescope picker directly. Can be used like:
    -- telescope = require('telescope.themes').get_ivy({...})
    telescope = require('telescope.themes').get_cursor({ winblend = 5 }),

    -- Used to override format_item. See :help dressing-format
    format_item_override = {},

    -- see :help dressing_get_config
    get_config = nil,
  },
})
```

**To Reproduce**

1. Use onedark vim theme (https://github.com/joshdick/onedark.vim)

**Screenshots**
![image](https://user-images.githubusercontent.com/8898038/171095713-cd8d9dfc-8036-4cde-a118-17b5a68762ff.png)

I've tried out a few colorschemes with dressing.nvim but cant seem to find a suitably visible border and title theme. 
Is it possible to change the input theme in the dressing config?

**Comment by stevearc** [comment]
onedark seems to not define the `NormalFloat` highlight (see `:help NormalFloat`). Try either doing `:highlight link NormalFloat Normal` or if you just want to configure it for the dressing windows, you can use winhighlight:
```lua
require('dressing').setup({
  input = {
    winhighlight = "NormalFloat:Normal",
  }
})
```

**Comment by nanozuki** [comment]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/4208028/171591184-a75389c4-f859-4dd4-81e1-4fbed426b10e.png">

I also have the same issue. I use the theme [rose-pine-dawn](https://github.com/rose-pine/neovim)

**Comment by cpea2506** [comment]
> onedark seems to not define the `NormalFloat` highlight (see `:help NormalFloat`). Try either doing `:highlight link NormalFloat Normal` or if you just want to configure it for the dressing windows, you can use winhighlight:
> 
> ```lua
> require('dressing').setup({
>   input = {
>     winhighlight = "NormalFloat:Normal",
>   }
> })
> ```

Thanks, i've been finding this for so long. Now it works as expected.

<img width="397" alt="Screen Shot 2022-06-02 at 15 53 11" src="https://user-images.githubusercontent.com/42694704/171593554-5d3d6bee-5959-459a-9e5d-dea21362e234.png">

**Comment by nanozuki** [comment]
After reading help `winhighlight` and `floatwin-api`, I found that I want to change the highlight of the floating windows' title. But I don't know what highlight group to replace...

**Comment by cpea2506** [comment]
> After reading help `winhighlight` and `floatwin-api`, I found that I want to change the highlight of the floating windows' title. But I don't know what highlight group to replace...

There are 3 things you can change

```
NormalFloat
FloatTitle
FloatBorder

**Comment by cpea2506** [comment]
> > There are 3 things you can change
> > ```
> > NormalFloat
> > FloatTitle
> > FloatBorder
> > ```
> 
> Ok, I see the 'rose pine' to set highlight as this:
> 
> ```
> FloatBorder  guifg=#dfdad9
> FloatTitle   links to FloatBorder
> NormalFloat  guifg=#575279 guibg=#fffaf3
> ```
> 
> They don't set the FloatTitle(FloatBorder)'s background, and the FloatTitle uses the background from NormalFloat. So the text is hard to recognize.

Ye. And i see that `rose-pine` has option for you to set these highlight: https://github.com/rose-pine/neovim#options

<img width="366" alt="Screen Shot 2022-06-02 at 21 24 13" src="https://user-images.githubusercontent.com/42694704/171651889-a40dd976-1921-4cd9-9868-17a10ea5d211.png">

**Comment by Firaenix** [comment]
Thank you very much for your help! I'm a neo/vim noob so I appreciate the swift response.
