### ISSUE TITLE
Is there any way to make my nvim-cmp panel transparent?

### ISSUE THREAD

**Issue by NEX-S** [stevearc/dressing.nvim#46]
I use default settings and seems dont work? Nvim-8.0.0dev

**Comment by stevearc** [comment]
I'm a bit confused by the question. Why do you think this plugin has anything to do with nvim-cmp?

**Comment by MRVAX** [comment]
sorry, i thought this plugin can let my neovim floating windows transparent like readme.md . My english is bad lol.

**Comment by MRVAX** [comment]
So is there any ways can make my floating windows transparent?

**Comment by stevearc** [comment]
Most windows use the `:help winblend` option to set transparency. For nvim-cmp, you may need to set `:help pumblend` instead
