### ISSUE TITLE
Support popui or allow extending for any custom plugin

### ISSUE THREAD

**Issue by entropitor** [stevearc/dressing.nvim#54]
It would be nice if https://github.com/hood/popui.nvim is supported. I like how for code actions, that UI is very close to the source. For others, I like this plugin

In general, It would be cool if users can add custom backends very easily

**Comment by stevearc** [comment]
If the desire is simply for putting the `vim.ui.select` UI next to the cursor, that's doable in the configuration for whichever backend you're currently using. Assuming it's the builtin, that would be
```lua
require('dressing').setup({
  select = {
    builtin = {
      relative = 'cursor',
    }
  }
})
```

If you only want the UI to be next to the cursor for code actions, then you can do this with the `get_config` callback (see `:help dressing_get_config`)

```lua
require('dressing').setup({
  select = {
    get_config = function(opts)
      if opts.kind == 'codeaction' then
        return {
          builtin = {
            relative = 'cursor',
          }
        }
      end
    end
  }
})
```

To address the broader question of more/custom backends: the only backends that make sense for dressing to support are selection UIs. If it's something like `popui`, well you can just use it directly without installing dressing at all. It's the same for defining custom backends. If you write a function that can take in the list of items and display a chooser, well you should just set that directly onto `vim.ui.select` and ignore dressing altogether. The purpose of dressing is to provide nicer default UIs, and to bridge the gap between the API of `vim.ui.select` and popular selection UIs like telescope and fzf.

**Comment by entropitor** [comment]
@stevearc Yes, I understand but I was hoping to use popui for codeactions and this plugin for the others

However, it doesn't seem to be possible, not even if I wrap dressing

```lua
  use({
    "stevearc/dressing.nvim",
    config = function()
      vim.ui.select = function(items, opts, on_choice)
        local kind = (opts or {}).kind
        if kind == "codeaction" then
          return require("popui.ui-overrider")(items, opts, on_choice)
        else
          return require("dressing.select")(items, opts, on_choice)
        end
      end
      require("dressing").setup({
        select = {
          enabled = false,
        },
      })
    end,
  })
```

If select.enabled = true, it overrides the vim.ui.select (even if I do the setup before the vim.ui.select). If it's false, I cannot use it because it falls back to the default [here](https://github.com/stevearc/dressing.nvim/blob/master/lua/dressing/select/init.lua#L35)

**Comment by stevearc** [comment]
Try this:
```lua
use({
  "stevearc/dressing.nvim",
  config = function()
    vim.ui.select = require("popui.ui-overrider")
    require("dressing").setup({
      select = {
        get_config = function(opts)
          if opts.kind == 'codeaction' then
            return {
              enabled = false
            }
          end
        end
      },
    })
  end,
})
```

**Comment by entropitor** [comment]
Seems to work 👍
