### ISSUE TITLE
Telescope doesn't show all items in selection menu

### ISSUE THREAD

**Issue by nimaipatel** [stevearc/dressing.nvim#56]
**Describe the bug**
The telescope front-end seems to omit one entry from the selection menu every time. 

**System information**

- OS: linux
- Neovim version: NVIM v0.8.0-dev-910-gc086bf6079
- Issue arises when using telescope for `vim.ui.select`
- Dressing config:

```lua
 require('dressing').setup {
    input = {
        winblend = 0,
    },
}

```
**Example**
```
vim.ui.select({'Hello', 'World'}, {}, function () end)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/53116839/185946228-e4d2e892-1117-49ef-a3e3-bec7daf60f32.png)

**Comment by stevearc** [comment]
I don't think it's omitting the entry, I think it's underneath the border characters of the input window. Your telescope UI looks different from mine; have you passed in any custom config for it?

![Screenshot from 2022-08-22 21-45-21](https://user-images.githubusercontent.com/506791/186071802-cac1d408-e9db-48fc-a499-b37e027be8ee.png)
 
It could be adversely interacting with the default config passed in by dressing (which is just the dropdown theme). You can use the default telescope picker with:
```lua
require('dressing').setup({
  select = {
    telescope = {}
  }
})
```

**Comment by nimaipatel** [comment]
Thanks for the quick comment. I tried disabling a bunch of plugins but still not sure what is causing the weird telescope theme.  Your solution works but it still doesn't seem to disable it which makes me think its just the default in latest telescope release, (although I might be wrong).
![image](https://user-images.githubusercontent.com/53116839/186222058-d9ebeeb2-50c1-48c4-b67f-2a3197abd10c.png)

The reason I raised the issue over here is because I don't seem to face the problem with telescope's inbuilt pickers. For example, here is `find_files`:
![image](https://user-images.githubusercontent.com/53116839/186222705-384d782f-f2d2-40a0-b478-b05d7a4c3b7d.png)

**Comment by stevearc** [comment]
Weird, yeah it definitely looks like an incorrect telescope config. I pulled the latest master before I tested and didn't see this, so I suspect it's some rogue plugin or config snippet that's modifying the telescope options. Can you try on a clean install with _just_ telescope and see if the windows still look like this?

You could also try adding a `print(debug.traceback())` inside of the `telescope.setup` function to see where it's getting called from, and verify that the config is what you expect.

**Comment by nimaipatel** [comment]
You are right, after some debugging I realized this is because of a global setting I had for floating windows. Thanks and sorry for wasting your time.
