### ISSUE TITLE
LSP Code Action Source

### ISSUE THREAD

**Issue by axieax** [stevearc/dressing.nvim#6]
Hello,
Just wondering if there is a way to include code action source names with `vim.lsp.buf.code_action()`, similar to Telescope's builtin lsp_code_actions.

vim-ui-select (with dressing.nvim)
![image](https://user-images.githubusercontent.com/62098008/146120934-33eb6d17-360a-4544-a52c-bbb264a18ae1.png)

Telescope
![image](https://user-images.githubusercontent.com/62098008/146120954-f322c3ad-2c48-42a0-acdc-bdc7d18c082d.png)

**Comment by stevearc** [comment]
At the moment, no. The display of lines is specified by the `opts.format_item` function that is passed in by the caller of `vim.ui.select`. In this case, it's [specified here](https://github.com/neovim/neovim/blob/4393360796ffd3ea6e552a13b19f60cd4892fbdc/runtime/lua/vim/lsp/buf.lua#L560-L563).

There are some different directions I could go from here. It would be fairly straightforward to add a `special_format` option to the config that lets you pass in a function that overrides `format_item` for a specific select kind (e.g. `opts.kind == 'codeaction'`). That would be enough to display the client name, but it wouldn't get you the nice highlighting or column alignment.

I could go further and build out the API to let you specify highlighting and column alignment as well, but then I have to make sure that it works (or at least behaves) across all the potential backends. It adds quite a bit of code complexity and diverges from the core API, so I'm hesitant to do it without good motivation.

I think the better way to go about it would be to make the case in Neovim core to officially add columns/highlighting to the `vim.ui.select` API. If something like that were standardized, I'd be way happier about implementing it.

Thoughts?

**Comment by axieax** [comment]
Hi thanks for your detailed response. I reckon before Neovim updates their core API, the best approach right now would be to override the format item.

**Comment by axieax** [comment]
Hi thanks for your detailed response. I reckon before Neovim updates their core API, the best approach right now would be to override the format item.

**Comment by stevearc** [comment]
Added a config option and also some example code in the help docs that should do what you want

**Comment by axieax** [comment]
Looks good thank you! Love how you can also filter by language server now :))

**Comment by axieax** [comment]
Hi @stevearc, just wondering, but is it possible to link the [LANGUAGE_SERVER] to the Comment highlight group? This would be amazing if possible :D

**Comment by axieax** [comment]
Yeah fair enough thanks for the clarification. Sometimes it's quite annoying that Telescope's code action doesn't do everything vim.lsp.buf.code_action would do (esp for nvim-jdtls), so I have to switch between both conditionally based on filetype. But yeah, perhaps I'll have a look into creating my own Telescope picker. Thanks again!

**Comment by axieax** [comment]
Hi, just wondering if this can now be achieved with e607dd99aeb5ce21e9a3d8f4c028650db12bd3af

**Comment by stevearc** [comment]
That commit was more intended for a different use case altogether, but it does technically unlock more UI customization abilities for end users as well (via the `get_config` override).

In this case though, I think I'm going to go back on my previous decision. I was stuck on trying to figure out how to keep the UI consistent across all of the backends, but (especially with that recent change) I don't think that's a hard requirement anymore. I'm more on board with small amounts of customization in certain circumstances for common or core neovim features.

So I've gone ahead and added a custom formatter when `kind = 'codeaction'`. Let me know if it works for you!

**Comment by axieax** [comment]
Thanks I love the change! Is it possible to search through the language server names (comment) as well?

**Comment by stevearc** [comment]
Done!

**Comment by axieax** [comment]
Thank you so much for the quick changes. Love your work as always!
