### ISSUE TITLE
Error running vim.ui.select in the fzf_lua backend the first time since nvim startup

### ISSUE THREAD

**Issue by Penaz91** [stevearc/dressing.nvim#64]
**Describe the bug**
The first time I use vim.ui.select after starting Nvim, I get an error similar to the following:

```
Error executing vim.schedule lua callback: ...cker/start/dressing.nvim/lua/dressing/select/fzf_lua.lua:30: attempt to call a nil value                                              
stack traceback:
        ...cker/start/dressing.nvim/lua/dressing/select/fzf_lua.lua:30: in function 'select'
        .../packer/start/dressing.nvim/lua/dressing/select/init.lua:63: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

This was triggered by using the `:lua vim.ui.select({1,2,3}, {}, function(opt)end)` command. Running the command again will work correctly

**System information**

- OS: Artix Linux
- Neovim version: 0.7.2
- Is this related to a specific `vim.ui.select` backend? If so, which one? Fzf_lua
- Dressing config: Default configuration

**To Reproduce**

1. Start Nvim
2. Use the following command `:lua vim.ui.select({1,2,3}, {}, function(opt)end)`
3. Dressing crashes
4. If you use the same command again, the command goes through correctly

**Additional context**
I'm using the following lua plugin related to FZF:
- https://github.com/ibhagwan/fzf-lua
- https://github.com/junegunn/fzf

**Comment by elijahdanko** [comment]
@Penaz91 @stevearc https://github.com/stevearc/dressing.nvim/pull/65 related

**Comment by stevearc** [comment]
This is a bug in fzf-lua. Fixed here: https://github.com/ibhagwan/fzf-lua/pull/522

**Comment by ibhagwan** [comment]
> This is a bug in fzf-lua. Fixed here: [ibhagwan/fzf-lua#522](https://github.com/ibhagwan/fzf-lua/pull/522)

Merged @stevearc’s PR, apologize for the mess.

**Comment by stevearc** [comment]
@ibhagwan no worries! Bugs happen :)

**Comment by stevearc** [comment]
Would love a PR to convert it to the best-practice API!

**Comment by ibhagwan** [comment]
https://github.com/stevearc/dressing.nvim/pull/67

Also took the liberty to improve upon the item number extraction using a lua regex :-)

**Comment by Penaz91** [comment]
Updated both fzf-lua and dressing to the latest commit, everything seems to be working perfectly.

It's great seeing such tight cooperation between different repository owners.

Thank you for everything, feel free to close!
