### ISSUE TITLE
[Feature] Default input string for `vim.ui.input`

### ISSUE THREAD

**Issue by pidgeon777** [stevearc/dressing.nvim#66]
It would be great to add an argument to `vim.ui.input` to specify the default text when asking the user for input.

**Comment by stevearc** [comment]
This already exists. Use `vim.ui.input({default = "my text"}, function() end)`. See `:help vim.ui.input` for more options.

**Comment by pidgeon777** [comment]
Would it be possible to do this also for `vim.ui.select`?

**Comment by stevearc** [comment]
`vim.ui.select` doesn't really have a concept of a "default" selection, but you can adjust the ordering of the items you pass in.
