### ISSUE TITLE
Using the FZF UIs removes the current visual selection

### ISSUE THREAD

**Issue by Penaz91** [stevearc/dressing.nvim#74]
**Describe the bug**
While trying to make a quick menu for nvim's LSP, I ran into the following issue: if you select some text and open vim.ui.* using dressing, the visual selection is lost.

**System information**

- OS: Linux
- Neovim version: 0.8.1
- Is this related to a specific `vim.ui.select` backend? If so, which one? Tested on vim.ui.select and vim.ui.input
- Dressing config:

```lua
require("dressing").setup{}
```

**To Reproduce**

1. Open a file containing some text
2. Select some text in visual mode (I usually use line-selection out of habit)
3. Trigger vim.ui in any way, the most "minimal code" i can provide is the following command

```
:'<,'>lua vim.ui.input({}, function(item) print(item) end)  
```
4. As soon as the ui pops up, the visual selection is lost.

**Additional context**
I tried disabling the plugin and using the native vim.ui.select and the selection is kept.

I'm using the fzf backend with `ibhagwan/fzf-lua`.

I'm available for any question!

**Comment by stevearc** [comment]
Unfortunately, this is just how vim works. When you open fzf, that puts your cursor inside of a terminal window in insert mode (technically, in "terminal" mode). There's no way to _also_ have your cursor be in the original window with a visual mode selection. You could potentially save the current visual selection before calling `vim.ui.select`, or you could restore the selection after `vim.ui.select` completes with `vim.cmd.normal({args = {"gv"}})`, but there's no way to preserve that visual selection while doing anything else with your cursor.

**Comment by Penaz91** [comment]
I understand. I thought it was an issue because the normal vim.ui seemed to keep the visual selection "active in background" (although probably only visually) and restore it after the task was completed.

Thank you for the clarification, feel free to close this ticket!

**Comment by JeanMertz** [comment]
I came across this issue recently while having issues with another plugin that used `vim.ui.input` while expecting a selection to be present. Should this perhaps be listed in the README as a drawback to this plugin compared to the built-in input handling?
