### ISSUE TITLE
Do not apply `sidescrolloff` to DressingInput

### ISSUE THREAD

**Issue by chrisgrieser** [stevearc/dressing.nvim#75]
**Describe the bug**
when you have a higher `sidescrolloff` value, this leads DressingInput to not using the entire width of the input window.

for the DressingInput window, `sidescrolloff` should be disabled or set to 0.

**To Reproduce**

1. set `vim.opt.sidescrolloff = 30`
2. run LSP rename (or anything else triggering dressing input)
3. fill a lot of characters

**Additional context**
this fixed it for me
```lua
augroup("dressing", {})
autocmd("FileType", {
	pattern = "DressingInput",
	group = "dressing",
	command = "setlocal sidescrolloff=0",
})
```

**Comment by stevearc** [comment]
I've refactored the config to allow passing in any window options you like. This should work for you now:
```lua
require("dressing").setup({
  input = {
    win_options = {
      sidescrolloff = 0,
    },
  },
})
})
