### ISSUE TITLE
side-scrolling with off-set for long input

### ISSUE THREAD

**Issue by jan-xyz** [stevearc/dressing.nvim#76]
Sometimes I find myself deleting too much of a text when for example renaming a file in `nvim-tree.lua` because I can't see the characters to the left. It would be really nice if I could configure the offset of characters to the left so that I can see what I'm deleting next.

<img width="365" alt="Screenshot 2022-12-07 at 07 56 32" src="https://user-images.githubusercontent.com/5249233/206109727-ca483e3d-a690-4163-93ce-8b1e80d23dab.png">

**Comment by stevearc** [comment]
This is a great use case for `:help sidescrolloff`. You can set that by passing it in as a window option
```lua
require("dressing").setup({
  input = {
    win_options = {
      sidescrolloff = 4,
    },
  },
})
```

**Comment by jan-xyz** [comment]
Uuuuhhh and here I thought I looked through all the docs. I didn't know Neovim comes packed with this! Thank you!

**Comment by meatballs** [comment]
@jan-xyz How did you get the input to extend beyond the nvim-tree buffer? Mine is always limited to the width of that buffer.
