### ISSUE TITLE
preview_width from telescope giving error

### ISSUE THREAD

**Issue by thalha-dev** [stevearc/dressing.nvim#77]
**Describe the bug**
setting preview_width option in telescope config giving an error every time I initialize the popup select window.

**System information**

- OS: [linux]
- Neovim version: 0.8.0
- Is this related to a specific `vim.ui.select` backend? If so, which one?  TELESCOPE
- Dressing config: SAME AS DEFAULT IN README

```lua
-- telescope config: preview_width option
telescope.setup({
	defaults = {
		--[[ layout_config = { width = 0.99, height = 0.99, preview_width = 0.6 }, ]] <----- THIS OPTION
		layout_config = { width = 0.99, height = 0.99 },

```

**Screenshots**
![image](https://user-images.githubusercontent.com/76985723/206626699-033cbd4e-7767-45a5-8835-4b1c5be8bb62.png)

**Comment by stevearc** [comment]
This is because `preview_width` is specific to one layout, not shared among all of them. You're only supposed to put shared options in the top level `setup()` config. See https://github.com/nvim-telescope/telescope.nvim/issues/1623 for more details.

**Comment by thalha-dev** [comment]
Thank you
