### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by horseinthesky** [stevearc/dressing.nvim#8]
Is it possible to set highlights for insert/select floating windows borders and text messages?

**Comment by stevearc** [comment]
You can customize the window border highlights by setting `FloatBorder` (by default it links to `VertSplit`, see `:help nvim_open_win`). I just made a commit that adds the `FloatTitle` highlight group that will highlight the window title for the input and the built-in select windows. By default it links to `FloatBorder`. There's another commit that highlights the text in the built-in `vim.ui.select` window with `DressingSelectText`, which links to `Normal` by default. Does that cover everything you wanted?

**Comment by horseinthesky** [comment]
Yeap. Now I can dress in to match my colorscheme. Thank you =)

**Comment by meijieru** [comment]
What about the input text area?

**Comment by stevearc** [comment]
Added a `DressingInputText` highlight group as well. Note that if the caller of `vim.ui.input` supplies a highlight function in the opts we will use that instead.

**Comment by meijieru** [comment]
It seems that the highlight group doesn't affect the background.
![image](https://user-images.githubusercontent.com/9511136/146663352-2ca702fc-a31e-4921-89a2-02faf25a3b57.png)
Any way to make the gray area disappear?

**Comment by stevearc** [comment]
I believe that the background of windows is typically set via `winhighlight` (e.g. `set winhighlight=Normal:MyNewGroup`). You can already do this with a FileType autocmd, but I'll expose a config option as well.

**Comment by meijieru** [comment]
Thx.
