### ISSUE TITLE
`vim.ui.select` error creating window when some string sent by the language server contains newline

### ISSUE THREAD

**Issue by goolord** [stevearc/dressing.nvim#88]
**Describe the bug**
dressing.nvim can fail to create a window when some string the language server sends contains newlines. this bug is also present in https://github.com/nvim-telescope/telescope-ui-select.nvim/issues/19

**System information**

- OS: mac
- Neovim version: v0.9.0-dev-2126+g84328bae0-dirty
- Telescope backend
- Dressing config:

```lua
require("dressing").setup()
```

**To Reproduce**

1. enter a project that does not build with HLS
2. wait for haskell language server to send error message + retry option

If possible, provide a minimal file that will trigger the issue (see
[tests/manual](https://github.com/stevearc/dressing.nvim/tree/master/tests/manual)
for examples of short ways to call `vim.ui.*`):

```
minimal code here
```

**Screenshots**
vanilla vim.ui.select:
![image](https://user-images.githubusercontent.com/24906808/221085415-8fd7ccc5-1deb-4f7c-9bb0-e02a37a18780.png)

dressing.nvim vim.ui.select:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/24906808/221085277-740344b3-d8c5-41f6-a4a3-f1c12a0767a8.png">

**Comment by stevearc** [comment]
Fixed!
