### ISSUE TITLE
telescope ui unexpected

### ISSUE THREAD

**Issue by jyf-111** [stevearc/dressing.nvim#93]
**Describe the bug**
- the telescope ui is dropdown and near cursor
- but in `select` i set ivy default,and cursor for code action
- it seems that when defaut is ivy,and indicate one as cursor, telescope ui will mess up
- if i change one of the two,everyting ok

<img width="600" alt="image" src="https://user-images.githubusercontent.com/77335030/227583927-415ef49a-55d0-4ffb-a35f-e645b87bacfc.png">

**System information**

- OS: windows
- Neovim version: v0.8.3
- Is this related to a specific `vim.ui.select` backend? If so, which one? Telescope
- Dressing config:

```lua
require("dressing").setup({
			input = {
				enabled = true,
				default_prompt = "Input:",
				prompt_align = "left",
				insert_only = true,
				start_in_insert = true,
				anchor = "SW",
				border = "single",
				relative = "cursor",
				prefer_width = 40,
				width = nil,
				max_width = { 140, 0.9 },
				min_width = { 20, 0.2 },
				buf_options = {},
				win_options = {
					winblend = 0,
					wrap = false,
				},
				mappings = {
					n = {
						["<Esc>"] = "Close",
						["<CR>"] = "Confirm",
					},
					i = {
						["<C-c>"] = "Close",
						["<CR>"] = "Confirm",
						["<Up>"] = "HistoryPrev",
						["<Down>"] = "HistoryNext",
					},
				},
				override = function(conf)
					return conf
				end,
			},
			select = {
				telescope = require("telescope.themes").get_ivy(),
				get_config = function(opts)
					if opts.kind == "codeaction" then
						return {
							telescope = require("telescope.themes").get_cursor({}),
						}
					elseif opts.kind == "overseer_template" then
						return {
							telescope = require("telescope.themes").get_cursor({}),
						}
					end
				end,
			},
		})
```

**To Reproduce**

1. set dressing config as before
2. code action

**Comment by stevearc** [comment]
I don't think I understand this bug report. The configuration you have specifies that telescope should use the "cursor" theme for code actions, and the screenshot shows a code action with the "cursor" theme. What is the problem?

**Comment by jyf-111** [comment]
sorry, my mistake.  I mix up three telescope theme. Thanks for you time.😹
