### ISSUE TITLE
Suggestion: `DressingInput` should use `listchars="precedes:…,extends:…"`

### ISSUE THREAD

**Issue by chrisgrieser** [stevearc/dressing.nvim#94]
I noticed that when I have entered text that is longer than the input window, the left side gets cut off, often leaving me confused. While I can (and did) set them via the `win_options` available, I think listchars to indicate text cut off make so much sesne that I'd suggest it should be set so by default.

```lua
input = {
	win_options = {
		list = true,
		listchars = "precedes:…,extends:…",
		sidescrolloff = 0, -- also reasonable default I think (see issue #76)
	},
},
```

**Comment by stevearc** [comment]
Good suggestion, thanks!
